name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_TOKEN }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t your-dockerhub-username/your-flask-app .
          docker push your-dockerhub-username/your-flask-app
